language: csharp
solution: ./Project/WebSite.sln
dotnet: 3.1.414

install:
  - nuget restore ./Project/WebSite.sln
  - sudo apt-get install nunit-console
  
script:
  - dotnet --info
  - dotnet build ./Project/WebSite.sln
